### ISSUE TITLE
Request for pretrained Sketchanet model

### ISSUE THREAD

**Issue by Vidu054** [jjkislele/SketchTriplet#1]
Hi.
I am working on SBIR model using Skechanet model using shoe2V dataset.. Since the dataset is too small I am not able to effectively train the network from scratch. Can you please share me if you have the pretrained Sketchanet model as you have used the same model.. This would help me saving the time. waiting for your positive responce.

**Comment by jjkislele** [comment]
You mean the model from papers:
- Yu, Qian, et al. "Sketch-a-net: A deep neural network that beats humans." International journal of computer vision 122.3 (2017): 411-425.
- Yu, Qian, et al. "Sketch me that shoe." Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2016.

Unfortunately, I don't have such a pre-trained model. I've been absent from the SBIR topic for almost 3 years (It's my master's study).

Moreover, I found some related repos that may help you:
- https://github.com/dasayan05/sketchanet-quickdraw (pyTorch version)
- https://github.com/seuliufeng/DeepSBIR (Tensorflow version)

**Comment by Vidu054** [comment]
Thanks you for your support, and will refer the link that you have
suggested...
